-- DiplomacyDealView_HoneyMacguffins
-- Author: mitch
-- DateCreated: 6/30/2023 10:37:30 AM
--------------------------------------------------------------
--print("UI diplomacy deal script was loaded");