

--TO DO I guess this should be done after I add in the actual macguffins
--TO DO add # completed to city built and wonder completed
INSERT INTO Parameters 
	    (ParameterId,															Name,											 Description,														 Domain,      DefaultValue, ConfigurationGroup,				ConfigurationId,										 GroupId, SortIndex) 
VALUES  ('PARAMETER_HONEY_MACGUFFIN_PASSIVE_FLAT_YIELD', 'LOC_PARAMETER_HONEY_MACGUFFIN_PASSIVE_FLAT_YIELD_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_PASSIVE_FLAT_YIELD_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_PASSIVE_FLAT_YIELD',               'AdvancedOptions', 601),

		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_PANTHEON', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_PANTHEON_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_PANTHEON_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_PANTHEON',               'AdvancedOptions', 602),
		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_POLITICAL_PHILOSOPHY', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_POLITICAL_PHILOSOPHY_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_POLITICAL_PHILOSOPHY_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_POLITICAL_PHILOSOPHY',               'AdvancedOptions', 603),
		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ENLIGHTENMENT', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ENLIGHTENMENT_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ENLIGHTENMENT_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_ENLIGHTENMENT',               'AdvancedOptions', 604),
		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ENVIORNMENTALISM', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ENVIORNMENTALISM_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ENVIORNMENTALISM_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_ENVIORNMENTALISM',               'AdvancedOptions', 605),
		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ASTRONOMY', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ASTRONOMY_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_ASTRONOMY_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_ASTRONOMY',               'AdvancedOptions', 606),
	    ('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_WONDER_COMPLETED', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_WONDER_COMPLETED_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_WONDER_COMPLETED_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_WONDER_COMPLETED',               'AdvancedOptions', 607),
		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_CITY_BUILT', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_CITY_BUILT_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_CITY_BUILT_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_CITY_BUILT',               'AdvancedOptions', 608),
		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_BOAT', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_BOAT_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_BOAT_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_BOAT',               'AdvancedOptions', 609),
		('PARAMETER_HONEY_MACGUFFIN_GRANT_ON_AIRPLANE', 'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_AIRPLANE_NAME',          'LOC_PARAMETER_HONEY_MACGUFFIN_GRANT_ON_AIRPLANE_DESCRIPTION',          'bool',           1,             'Game',			  'CONFIG_HONEY_MACGUFFIN_GRANT_ON_AIRPLANE',               'AdvancedOptions', 610);


