-- Honey_Macguffin_Active_FlatYields
-- Author: Honey The Bear
-- DateCreated: 7/17/2023 6:29:11 PM
--------------------------------------------------------------


INSERT INTO Types 

		(Type, Kind)
VALUES  ('GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE',				'KIND_GREATWORK'),
		('GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER2',				'KIND_GREATWORK'),
		('GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER3',				'KIND_GREATWORK'),
		('GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_GP',				'KIND_GREAT_PERSON_INDIVIDUAL'),
		('GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER2_GP',				'KIND_GREAT_PERSON_INDIVIDUAL'),
		('GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER3_GP',				'KIND_GREAT_PERSON_INDIVIDUAL');



INSERT INTO GreatPersonIndividuals
			(GreatPersonIndividualType,						Name,						GreatPersonClassType,			 eraType,					Gender,		 ActionCharges,            ActionEffectTextOverride)
VALUES ('GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_GP', 'LOC_GREAT_PERSON_HONEY_MACGUFFIN_GP_NAME',  'GREAT_PERSON_HONEY_MACGUFFIN_GP' ,     'HONEY_MACGUFFIN_DUMMY_ERA',        'M',            0,					'LOC_GREAT_PERSON_HONEY_MACGUFFIN_ACTION'),
	   ('GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER2_GP', 'LOC_GREAT_PERSON_HONEY_MACGUFFIN_GP_NAME',  'GREAT_PERSON_HONEY_MACGUFFIN_GP' ,     'HONEY_MACGUFFIN_DUMMY_ERA',        'M',            0,					'LOC_GREAT_PERSON_HONEY_MACGUFFIN_ACTION'),
	   ('GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER3_GP', 'LOC_GREAT_PERSON_HONEY_MACGUFFIN_GP_NAME',  'GREAT_PERSON_HONEY_MACGUFFIN_GP' ,     'HONEY_MACGUFFIN_DUMMY_ERA',        'M',            0,					'LOC_GREAT_PERSON_HONEY_MACGUFFIN_ACTION');

INSERT INTO GreatWorks
		(GreatWorkType,																										 Name,									      GreatPersonIndividualType,							 GreatWorkObjectType,																			 Quote ,          Tourism )
VALUES  ('GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE',     'LOC_GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_NAME',   'GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_GP',			'GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE',										'LOC_GREATWORK_HOMER_2_QUOTE',           0 ),
		('GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER2',     'LOC_GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER2_NAME',   'GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER2_GP',			'GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE',										'LOC_GREATWORK_HOMER_2_QUOTE',           0 ),
		('GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER3',     'LOC_GREATWORK_GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER3_NAME',   'GREAT_PERSON_HONEY_MACGUFFIN_ACTIVE_FLAT_SCIENCE_TIER3_GP',			'GREATWORKOBJECT_HONEY_MACGUFFIN_ACTIVE',										'LOC_GREATWORK_HOMER_2_QUOTE',           0 );