-- Honey_Macguffin_Passive_Government_Policies
-- Author: mitch
-- DateCreated: 8/19/2023 9:01:17 AM
--------------------------------------------------------------

-- + military slots
-- + economic slots
-- + diplomatic slots
-- + wildcard slots
-- nice military policy 1
-- nice military policy 2
-- nice economic policy 1 -- more trade routes, trade routes offer more gold
-- nice economic policy 2 -- all districts 150% adjacency bonus
-- nice diplomatic policy 1 -- spy bonus
-- nice diplomatic policy 2
-- nice wildcard 1
-- nice wildcard 2